// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type MessageBody byte

const (
	MessageBodyNONE        MessageBody = 0
	MessageBodyApp         MessageBody = 1
	MessageBodyAppReply    MessageBody = 2
	MessageBodyTransaction MessageBody = 3
)

var EnumNamesMessageBody = map[MessageBody]string{
	MessageBodyNONE:        "NONE",
	MessageBodyApp:         "App",
	MessageBodyAppReply:    "AppReply",
	MessageBodyTransaction: "Transaction",
}

var EnumValuesMessageBody = map[string]MessageBody{
	"NONE":        MessageBodyNONE,
	"App":         MessageBodyApp,
	"AppReply":    MessageBodyAppReply,
	"Transaction": MessageBodyTransaction,
}

func (v MessageBody) String() string {
	if s, ok := EnumNamesMessageBody[v]; ok {
		return s
	}
	return "MessageBody(" + strconv.FormatInt(int64(v), 10) + ")"
}
